import { z } from 'zod'

export const settingsSchema = z.object({
    basic: z.object({
        siteName: z.string().trim().min(1, 'Site name is required'),
        siteKey: z.string().trim().min(1, 'Site key is required'),
        isDeleted: z.boolean().default(false),
        name: z.string().trim().optional(),
        isLive: z.boolean().default(true),
        maintenanceMode: z.boolean().default(false),
        siteTimezone: z.string().trim().default('UTC'),
        siteLocale: z.string().trim().default('en-US'),
        defaultPageSize: z.number().min(1, 'Page size must be at least 1').default(20),
        maxUploadSizeMB: z.number().min(1, 'Upload size must be at least 1').default(10),
    }),
    contactInfo: z.object({
        email: z.string().trim().email('Invalid email address'),
        phone: z.string().trim().optional(),
        address: z.object({
            street: z.string().trim().optional(),
            city: z.string().trim().optional(),
            state: z.string().trim().optional(),
            zipCode: z.string().trim().optional(),
            country: z.string().trim().optional(),
        }),
        supportEmail: z.string().trim().optional(),
        supportPhone: z.string().trim().optional(),
        contactHours: z.string().trim().optional(),
    }),
    branding: z.object({
        logo: z.string().trim().optional(),
        favicon: z.string().trim().optional(),
        themeColor: z.string().trim().default('#000000'),
        customCSSUrl: z.string().trim().optional(),
        customJSUrl: z.string().trim().optional(),
    }),
    shipping: z.object({
        shippingOptions: z.string().trim().optional(),
        shippingMethods: z.string().trim().optional(),
        minOrderAmount: z.number().min(0).default(0),
        maxOrderAmount: z.number().optional(),
        freeShippingThreshold: z.number().min(0).default(100),
        shippingHandlingFee: z.number().min(0).default(5),
        shippingInsuranceEnabled: z.boolean().default(false),
    }),
    email: z.object({
        smtpHost: z.string().trim().optional(),
        smtpPort: z.number().optional(),
        smtpUser: z.string().trim().optional(),
        smtpPassword: z.string().trim().optional(),
        templates: z.object({
            orderConfirmation: z.string().trim().optional(),
            passwordReset: z.string().trim().optional(),
            shippingNotification: z.string().trim().optional(),
            promotional: z.string().trim().optional(),
        }),
        emailSenderName: z.string().trim().optional(),
        emailSenderAddress: z.string().trim().optional(),
    }),
    seo: z.object({
        title: z.string().trim().optional(),
        description: z.string().trim().optional(),
        keywords: z.string().trim().optional(),
        googleSiteVerification: z.string().trim().optional(),
        robotsTxt: z.string().trim().optional(),
    }),
    analytics: z.object({
        googleAnalyticsID: z.string().trim().optional(),
        facebookPixelID: z.string().trim().optional(),
        hotjarID: z.string().trim().optional(),
        segmentWriteKey: z.string().trim().optional(),
    }),
    currencySettings: z.object({
        currency: z.string().trim().default('USD'),
        currencySymbol: z.string().trim().default('$'),
        taxRate: z.number().min(0).default(0),
        taxEnabled: z.boolean().default(false),
        taxInclusivePricing: z.boolean().default(false),
    }),
    payment: z.object({
        paymentMethods: z.string().trim().optional(),
        enabledMFA: z.boolean().default(false),
        defaultPaymentMethod: z.string().trim().optional(),
        stripePublicKey: z.string().trim().optional(),
        stripeSecretKey: z.string().trim().optional(),
        paypalClientId: z.string().trim().optional(),
        paypalSecret: z.string().trim().optional(),
        currencyConversionEnabled: z.boolean().default(false),
    }),
    socialMediaLinks: z.object({
        facebook: z.string().trim().url().optional(),
        twitter: z.string().trim().url().optional(),
        instagram: z.string().trim().url().optional(),
        linkedin: z.string().trim().url().optional(),
        youtube: z.string().trim().url().optional(),
        pinterest: z.string().trim().url().optional(),
        tiktok: z.string().trim().url().optional(),
    }),
    featuredCategories: z.string().trim().optional(),
    loyaltyProgram: z.object({
        enabled: z.boolean().default(false),
        pointsPerDollar: z.number().min(0).default(1),
        tieredRewardsEnabled: z.boolean().default(false),
        extraRewardMultiplier: z.number().min(1).default(1),
    }),
    policies: z.object({
        returnPolicy: z.string().trim().optional(),
        privacyPolicy: z.string().trim().optional(),
        termsOfService: z.string().trim().optional(),
        cookiePolicy: z.string().trim().optional(),
        gdprComplianceEnabled: z.boolean().default(false),
    }),
    security: z.object({
        passwordMinLength: z.number().min(1).default(8),
        passwordRequireSymbols: z.boolean().default(true),
        passwordRequireNumbers: z.boolean().default(true),
        passwordRequireUppercase: z.boolean().default(true),
        maxLoginAttempts: z.number().min(1).default(5),
        accountLockoutDurationMinutes: z.number().min(0).default(30),
        sessionTimeoutMinutes: z.number().min(0).default(60),
        refreshTokenExpiryDays: z.number().min(1).default(30),
        enableCaptchaOnLogin: z.boolean().default(false),
        enableCaptchaOnSignup: z.boolean().default(false),
        enableIPRateLimiting: z.boolean().default(true),
        maxRequestsPerMinute: z.number().min(1).default(60),
        allowedIPRanges: z.string().trim().optional(),
        auditLoggingEnabled: z.boolean().default(true),
        twoFactorAuthRequired: z.boolean().default(false),
        jwtSecret: z.string().trim().optional(),
        jwtExpiryMinutes: z.number().min(1).default(60),
        passwordResetTokenExpiryMinutes: z.number().min(1).default(15),
    }),
    misc: z.object({
        allowGuestCheckout: z.boolean().default(true),
        enableDarkMode: z.boolean().default(false),
        defaultLanguage: z.string().trim().default('en'),
        supportedLanguages: z.string().trim().default('en'),
        defaultPageSize: z.number().min(1).default(20),
        maxUploadSizeMB: z.number().min(1).default(10),
        enablePushNotifications: z.boolean().default(false),
        notificationSound: z.string().trim().default('default'),
        customCSSUrl: z.string().trim().optional(),
        customJSUrl: z.string().trim().optional(),
    })
})

export type SettingsFormData = z.infer<typeof settingsSchema>