export const baseurl = process.env.NEXT_PUBLIC_BASE_URL
export const appUrl = process.env.NEXT_PUBLIC_APP_URL
export const secret = process.env.NEXT_PUBLIC_SECRET
export const googleClient=process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID
export const googleSecret=process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET
export const githubClient=process.env.NEXT_PUBLIC_GITHUB_ID
export const githubSecret=process.env.NEXT_PUBLIC_GITHUB_SECRET
export const facebookClient=process.env.NEXT_PUBLIC_FACEBOOK_CLIENT_ID
export const facebookSecret=process.env.NEXT_PUBLIC_FACEBOOK_CLIENT_SECRET
export const razorPayPublic = process.env.NEXT_PUBLIC_ROZORPAY_PUBLIC_KEY;
export const linkedinClient =""
export const linkedinSecret =""
export const twitterClient =""
export const twitterSecret =""
export const oidcClient =""
export const oidcIssuer =""
export const sitekey =process.env.NEXT_PUBLIC_SITEKEY